#baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'The U2F Garden'

[languages]
[languages.en]
  title = "The U2F Garden"

[params]
  description = "The U2F Garden is a catalog of U2F tokens"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/posts/"
  weight = 1
  [[menu.nav]]
  name = "Keys"
  url = "/keys/"
  weight=1
  [[menu.nav]]
  name = "FAQ"
  url= "/faq/"
  weight=3
  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3

[taxonomies]
  type="type"
  feature="features"
  vendor="vendor"
  interface="interfaces"
  tag="tags"
  family="family"
